; Auto-generated. Do not edit!


(cl:in-package srs_decision_making-msg)


;//! \htmlinclude ExecutionResult.msg.html

(cl:defclass <ExecutionResult> (roslisp-msg-protocol:ros-message)
  ((return_value
    :reader return_value
    :initarg :return_value
    :type cl:integer
    :initform 0))
)

(cl:defclass ExecutionResult (<ExecutionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecutionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecutionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name srs_decision_making-msg:<ExecutionResult> is deprecated: use srs_decision_making-msg:ExecutionResult instead.")))

(cl:ensure-generic-function 'return_value-val :lambda-list '(m))
(cl:defmethod return_value-val ((m <ExecutionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader srs_decision_making-msg:return_value-val is deprecated.  Use srs_decision_making-msg:return_value instead.")
  (return_value m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecutionResult>) ostream)
  "Serializes a message object of type '<ExecutionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'return_value)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'return_value)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'return_value)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'return_value)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecutionResult>) istream)
  "Deserializes a message object of type '<ExecutionResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'return_value)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'return_value)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'return_value)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'return_value)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecutionResult>)))
  "Returns string type for a message object of type '<ExecutionResult>"
  "srs_decision_making/ExecutionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecutionResult)))
  "Returns string type for a message object of type 'ExecutionResult"
  "srs_decision_making/ExecutionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecutionResult>)))
  "Returns md5sum for a message object of type '<ExecutionResult>"
  "a43395adce0eb50d87dd179dfd3f466a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecutionResult)))
  "Returns md5sum for a message object of type 'ExecutionResult"
  "a43395adce0eb50d87dd179dfd3f466a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecutionResult>)))
  "Returns full string definition for message of type '<ExecutionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#define the result~%uint32 return_value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecutionResult)))
  "Returns full string definition for message of type 'ExecutionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#define the result~%uint32 return_value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecutionResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecutionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecutionResult
    (cl:cons ':return_value (return_value msg))
))
