; Auto-generated. Do not edit!


(cl:in-package srs_decision_making-msg)


;//! \htmlinclude UserResult.msg.html

(cl:defclass <UserResult> (roslisp-msg-protocol:ros-message)
  ((returnValue
    :reader returnValue
    :initarg :returnValue
    :type cl:integer
    :initform 0))
)

(cl:defclass UserResult (<UserResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <UserResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'UserResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name srs_decision_making-msg:<UserResult> is deprecated: use srs_decision_making-msg:UserResult instead.")))

(cl:ensure-generic-function 'returnValue-val :lambda-list '(m))
(cl:defmethod returnValue-val ((m <UserResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader srs_decision_making-msg:returnValue-val is deprecated.  Use srs_decision_making-msg:returnValue instead.")
  (returnValue m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <UserResult>) ostream)
  "Serializes a message object of type '<UserResult>"
  (cl:let* ((signed (cl:slot-value msg 'returnValue)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <UserResult>) istream)
  "Deserializes a message object of type '<UserResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'returnValue) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<UserResult>)))
  "Returns string type for a message object of type '<UserResult>"
  "srs_decision_making/UserResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'UserResult)))
  "Returns string type for a message object of type 'UserResult"
  "srs_decision_making/UserResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<UserResult>)))
  "Returns md5sum for a message object of type '<UserResult>"
  "79bcbdb878527c07352071437fc60f47")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'UserResult)))
  "Returns md5sum for a message object of type 'UserResult"
  "79bcbdb878527c07352071437fc60f47")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<UserResult>)))
  "Returns full string definition for message of type '<UserResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 returnValue~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'UserResult)))
  "Returns full string definition for message of type 'UserResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 returnValue~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <UserResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <UserResult>))
  "Converts a ROS message object to a list"
  (cl:list 'UserResult
    (cl:cons ':returnValue (returnValue msg))
))
