/* Auto-generated by genmsg_cpp for file /home/lei/git/care-o-bot/srs_public/srs_decision_making/msg/ExecutionResult.msg */
#ifndef SRS_DECISION_MAKING_MESSAGE_EXECUTIONRESULT_H
#define SRS_DECISION_MAKING_MESSAGE_EXECUTIONRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace srs_decision_making
{
template <class ContainerAllocator>
struct ExecutionResult_ {
  typedef ExecutionResult_<ContainerAllocator> Type;

  ExecutionResult_()
  : return_value(0)
  {
  }

  ExecutionResult_(const ContainerAllocator& _alloc)
  : return_value(0)
  {
  }

  typedef uint32_t _return_value_type;
  uint32_t return_value;


private:
  static const char* __s_getDataType_() { return "srs_decision_making/ExecutionResult"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a43395adce0eb50d87dd179dfd3f466a"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#define the result\n\
uint32 return_value\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, return_value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, return_value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(return_value);
    return size;
  }

  typedef boost::shared_ptr< ::srs_decision_making::ExecutionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srs_decision_making::ExecutionResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ExecutionResult
typedef  ::srs_decision_making::ExecutionResult_<std::allocator<void> > ExecutionResult;

typedef boost::shared_ptr< ::srs_decision_making::ExecutionResult> ExecutionResultPtr;
typedef boost::shared_ptr< ::srs_decision_making::ExecutionResult const> ExecutionResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::srs_decision_making::ExecutionResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::srs_decision_making::ExecutionResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace srs_decision_making

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::srs_decision_making::ExecutionResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::srs_decision_making::ExecutionResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::srs_decision_making::ExecutionResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a43395adce0eb50d87dd179dfd3f466a";
  }

  static const char* value(const  ::srs_decision_making::ExecutionResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa43395adce0eb50dULL;
  static const uint64_t static_value2 = 0x87dd179dfd3f466aULL;
};

template<class ContainerAllocator>
struct DataType< ::srs_decision_making::ExecutionResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "srs_decision_making/ExecutionResult";
  }

  static const char* value(const  ::srs_decision_making::ExecutionResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::srs_decision_making::ExecutionResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#define the result\n\
uint32 return_value\n\
\n\
";
  }

  static const char* value(const  ::srs_decision_making::ExecutionResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::srs_decision_making::ExecutionResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::srs_decision_making::ExecutionResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.return_value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ExecutionResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srs_decision_making::ExecutionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::srs_decision_making::ExecutionResult_<ContainerAllocator> & v) 
  {
    s << indent << "return_value: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.return_value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SRS_DECISION_MAKING_MESSAGE_EXECUTIONRESULT_H

