/* Auto-generated by genmsg_cpp for file /home/lei/git/care-o-bot/srs_public/srs_decision_making/msg/Last_step_info.msg */
#ifndef SRS_DECISION_MAKING_MESSAGE_LAST_STEP_INFO_H
#define SRS_DECISION_MAKING_MESSAGE_LAST_STEP_INFO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace srs_decision_making
{
template <class ContainerAllocator>
struct Last_step_info_ {
  typedef Last_step_info_<ContainerAllocator> Type;

  Last_step_info_()
  : step_name()
  , outcome()
  , semi_autonomous_mode(false)
  {
  }

  Last_step_info_(const ContainerAllocator& _alloc)
  : step_name(_alloc)
  , outcome(_alloc)
  , semi_autonomous_mode(false)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _step_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  step_name;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _outcome_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  outcome;

  typedef uint8_t _semi_autonomous_mode_type;
  uint8_t semi_autonomous_mode;


private:
  static const char* __s_getDataType_() { return "srs_decision_making/Last_step_info"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d3e1336fdd2e5ea9111bd37f49150507"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string step_name\n\
string outcome\n\
bool semi_autonomous_mode\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, step_name);
    ros::serialization::serialize(stream, outcome);
    ros::serialization::serialize(stream, semi_autonomous_mode);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, step_name);
    ros::serialization::deserialize(stream, outcome);
    ros::serialization::deserialize(stream, semi_autonomous_mode);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(step_name);
    size += ros::serialization::serializationLength(outcome);
    size += ros::serialization::serializationLength(semi_autonomous_mode);
    return size;
  }

  typedef boost::shared_ptr< ::srs_decision_making::Last_step_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srs_decision_making::Last_step_info_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Last_step_info
typedef  ::srs_decision_making::Last_step_info_<std::allocator<void> > Last_step_info;

typedef boost::shared_ptr< ::srs_decision_making::Last_step_info> Last_step_infoPtr;
typedef boost::shared_ptr< ::srs_decision_making::Last_step_info const> Last_step_infoConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::srs_decision_making::Last_step_info_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::srs_decision_making::Last_step_info_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace srs_decision_making

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::srs_decision_making::Last_step_info_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::srs_decision_making::Last_step_info_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::srs_decision_making::Last_step_info_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d3e1336fdd2e5ea9111bd37f49150507";
  }

  static const char* value(const  ::srs_decision_making::Last_step_info_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd3e1336fdd2e5ea9ULL;
  static const uint64_t static_value2 = 0x111bd37f49150507ULL;
};

template<class ContainerAllocator>
struct DataType< ::srs_decision_making::Last_step_info_<ContainerAllocator> > {
  static const char* value() 
  {
    return "srs_decision_making/Last_step_info";
  }

  static const char* value(const  ::srs_decision_making::Last_step_info_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::srs_decision_making::Last_step_info_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string step_name\n\
string outcome\n\
bool semi_autonomous_mode\n\
";
  }

  static const char* value(const  ::srs_decision_making::Last_step_info_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::srs_decision_making::Last_step_info_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.step_name);
    stream.next(m.outcome);
    stream.next(m.semi_autonomous_mode);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Last_step_info_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srs_decision_making::Last_step_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::srs_decision_making::Last_step_info_<ContainerAllocator> & v) 
  {
    s << indent << "step_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.step_name);
    s << indent << "outcome: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.outcome);
    s << indent << "semi_autonomous_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.semi_autonomous_mode);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SRS_DECISION_MAKING_MESSAGE_LAST_STEP_INFO_H

