/* Auto-generated by genmsg_cpp for file /home/lei/git/care-o-bot/srs_public/srs_decision_making/msg/UserResult.msg */
#ifndef SRS_DECISION_MAKING_MESSAGE_USERRESULT_H
#define SRS_DECISION_MAKING_MESSAGE_USERRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace srs_decision_making
{
template <class ContainerAllocator>
struct UserResult_ {
  typedef UserResult_<ContainerAllocator> Type;

  UserResult_()
  : returnValue(0)
  {
  }

  UserResult_(const ContainerAllocator& _alloc)
  : returnValue(0)
  {
  }

  typedef int32_t _returnValue_type;
  int32_t returnValue;


private:
  static const char* __s_getDataType_() { return "srs_decision_making/UserResult"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "79bcbdb878527c07352071437fc60f47"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 returnValue\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, returnValue);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, returnValue);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(returnValue);
    return size;
  }

  typedef boost::shared_ptr< ::srs_decision_making::UserResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srs_decision_making::UserResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct UserResult
typedef  ::srs_decision_making::UserResult_<std::allocator<void> > UserResult;

typedef boost::shared_ptr< ::srs_decision_making::UserResult> UserResultPtr;
typedef boost::shared_ptr< ::srs_decision_making::UserResult const> UserResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::srs_decision_making::UserResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::srs_decision_making::UserResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace srs_decision_making

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::srs_decision_making::UserResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::srs_decision_making::UserResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::srs_decision_making::UserResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "79bcbdb878527c07352071437fc60f47";
  }

  static const char* value(const  ::srs_decision_making::UserResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x79bcbdb878527c07ULL;
  static const uint64_t static_value2 = 0x352071437fc60f47ULL;
};

template<class ContainerAllocator>
struct DataType< ::srs_decision_making::UserResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "srs_decision_making/UserResult";
  }

  static const char* value(const  ::srs_decision_making::UserResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::srs_decision_making::UserResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 returnValue\n\
\n\
";
  }

  static const char* value(const  ::srs_decision_making::UserResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::srs_decision_making::UserResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::srs_decision_making::UserResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.returnValue);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct UserResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srs_decision_making::UserResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::srs_decision_making::UserResult_<ContainerAllocator> & v) 
  {
    s << indent << "returnValue: ";
    Printer<int32_t>::stream(s, indent + "  ", v.returnValue);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SRS_DECISION_MAKING_MESSAGE_USERRESULT_H

