/* Auto-generated by genmsg_cpp for file /home/lei/git/care-o-bot/srs_public/srs_decision_making/msg/UserFeedback.msg */
#ifndef SRS_DECISION_MAKING_MESSAGE_USERFEEDBACK_H
#define SRS_DECISION_MAKING_MESSAGE_USERFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace srs_decision_making
{
template <class ContainerAllocator>
struct UserFeedback_ {
  typedef UserFeedback_<ContainerAllocator> Type;

  UserFeedback_()
  : currentState()
  , solutionRequired(false)
  , exceptionalCase_id(0)
  {
  }

  UserFeedback_(const ContainerAllocator& _alloc)
  : currentState(_alloc)
  , solutionRequired(false)
  , exceptionalCase_id(0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _currentState_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  currentState;

  typedef uint8_t _solutionRequired_type;
  uint8_t solutionRequired;

  typedef uint32_t _exceptionalCase_id_type;
  uint32_t exceptionalCase_id;


private:
  static const char* __s_getDataType_() { return "srs_decision_making/UserFeedback"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "acf8a34fbff89b074eef6dd5f9a86b7d"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
string currentState\n\
bool solutionRequired\n\
uint32 exceptionalCase_id\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, currentState);
    ros::serialization::serialize(stream, solutionRequired);
    ros::serialization::serialize(stream, exceptionalCase_id);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, currentState);
    ros::serialization::deserialize(stream, solutionRequired);
    ros::serialization::deserialize(stream, exceptionalCase_id);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(currentState);
    size += ros::serialization::serializationLength(solutionRequired);
    size += ros::serialization::serializationLength(exceptionalCase_id);
    return size;
  }

  typedef boost::shared_ptr< ::srs_decision_making::UserFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srs_decision_making::UserFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct UserFeedback
typedef  ::srs_decision_making::UserFeedback_<std::allocator<void> > UserFeedback;

typedef boost::shared_ptr< ::srs_decision_making::UserFeedback> UserFeedbackPtr;
typedef boost::shared_ptr< ::srs_decision_making::UserFeedback const> UserFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::srs_decision_making::UserFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::srs_decision_making::UserFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace srs_decision_making

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::srs_decision_making::UserFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::srs_decision_making::UserFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::srs_decision_making::UserFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "acf8a34fbff89b074eef6dd5f9a86b7d";
  }

  static const char* value(const  ::srs_decision_making::UserFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xacf8a34fbff89b07ULL;
  static const uint64_t static_value2 = 0x4eef6dd5f9a86b7dULL;
};

template<class ContainerAllocator>
struct DataType< ::srs_decision_making::UserFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "srs_decision_making/UserFeedback";
  }

  static const char* value(const  ::srs_decision_making::UserFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::srs_decision_making::UserFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
string currentState\n\
bool solutionRequired\n\
uint32 exceptionalCase_id\n\
\n\
\n\
";
  }

  static const char* value(const  ::srs_decision_making::UserFeedback_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::srs_decision_making::UserFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.currentState);
    stream.next(m.solutionRequired);
    stream.next(m.exceptionalCase_id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct UserFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srs_decision_making::UserFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::srs_decision_making::UserFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "currentState: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.currentState);
    s << indent << "solutionRequired: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solutionRequired);
    s << indent << "exceptionalCase_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.exceptionalCase_id);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SRS_DECISION_MAKING_MESSAGE_USERFEEDBACK_H

